export type Provider = "openai" | "gemini" | "claude"

export type TopicInput = { topic: string; audience: string; slideCount: number; style: string }
export type SlideOutline = { id: string; title: string; purpose: string; keyPoints: string[]; visualHint: string }
export type PresentationOutline = { title: string; theme: string; audience: string; style: string; slides: SlideOutline[] }
export type SlideSVG = { slideId: string; title: string; svg: string }
export type EffectiveQuota = { date: string; dailyPPTLimit: number; dailySlideLimit: number; pptUsed: number; slidesUsed: number; pptReserved: number; slidesReserved: number; pptRemaining: number; slidesRemaining: number; source: "user" | "group"; groupId: string; groupName: string }
export type SVGResponse = { slides: SlideSVG[]; quota?: EffectiveQuota }
export type UserRole = "admin" | "user"
export type User = { id: string; email: string; username: string; role: UserRole; disabled: boolean; groupId: string; dailyPPTLimit?: number | null; dailySlideLimit?: number | null; createdAt: string; updatedAt: string }
export type UserGroup = { id: string; name: string; description: string; dailyPPTLimit: number; dailySlideLimit: number; isDefault: boolean; createdAt: string; updatedAt: string }
export type SystemSettings = { registrationEnabled: boolean; defaultUserGroupId: string; updatedAt: string; updatedBy: string }
export type StorageKind = "json" | "sqlite" | "postgres" | "mysql" | "redis"
export type StorageConfig = { kind: StorageKind | ""; path?: string; dsn?: string; updatedAt?: string }
export type SupportedStorageOption = { kind: StorageKind; label: string; status: "supported" | "advanced" | "comingSoon" | "notPrimaryStore"; defaultPath?: string; description: string }
export type SetupStatus = { needsSetup: boolean; storageConfigured?: boolean; storage?: StorageConfig; supportedStorage?: SupportedStorageOption[] }
export type AuthResponse = { user: User }
export type ModelConfig = { provider: Provider; apiKey: string; baseURL: string; model: string }
export type GenerationRoleSettings = { systemPrompt: string; supportsTools: boolean; modelConfig: ModelConfig }
export type PromptSettings = { architect: GenerationRoleSettings; svg: GenerationRoleSettings; updatedAt: string; updatedBy: string }
